somes fix MDEFINE -> HDEFINE etc.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2715,7 +2715,124 @@ fi
 rm -f conftest.c $testdir/conftest$EXECSUFFIX
 if [ "${HAVE_SYSLOG_H}" = "yes" ]
  then
-    echo "yeaaaaA"
+HAVE_CODE="1"
+echo "#ifndef HAVE_CODE" > config/have_code.h
+echo "#define HAVE_CODE \"$HAVE_CODE\"" >> config/have_code.h
+echo "#endif" >> config/have_code.h
+echo "hdefs[\"HAVE_CODE\"] = \"$HAVE_CODE\"" >>configure.lua
+fi
+$ECHO_N "checking for <paths.h> (HAVE_PATHS_H)..."
+$ECHO_N "checking for <paths.h> (HAVE_PATHS_H)..." >> config.log
+MK_CACHED="No"
+MK_COMPILE_STATUS="OK"
+if [ "${cache}" != "" ]; then
+	if [ -e "${cache}/ctest-HAVE_PATHS_H" ]; then
+		HAVE_PATHS_H=`cat ${cache}/ctest-HAVE_PATHS_H`
+		MK_COMPILE_STATUS=`cat ${cache}/ctest-status-HAVE_PATHS_H`
+		MK_CACHED="Yes"
+	fi
+fi
+if [ "${MK_CACHED}" = "No" ]; then
+	cat << EOT > conftest.c
+#include <paths.h>
+int main (int argc, char *argv[]) { return (0); }
+
+EOT
+	echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+	$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+	if [ $? != 0 ]; then
+		echo "-> failed ($?)" >> config.log
+		MK_COMPILE_STATUS="FAIL($?)"
+	fi
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_PATHS_H="yes"
+echo "HAVE_PATHS_H=$HAVE_PATHS_H" >>Makefile.config
+echo "mdefs[\"HAVE_PATHS_H\"] = \"$HAVE_PATHS_H\"" >>configure.lua
+echo "#ifndef HAVE_PATHS_H" > config/have_paths_h.h
+echo "#define HAVE_PATHS_H \"$HAVE_PATHS_H\"" >> config/have_paths_h.h
+echo "#endif" >> config/have_paths_h.h
+echo "hdefs[\"HAVE_PATHS_H\"] = \"$HAVE_PATHS_H\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE_PATHS_H="no"
+echo "HAVE_PATHS_H=$HAVE_PATHS_H" >>Makefile.config
+echo "mdefs[\"HAVE_PATHS_H\"] = \"$HAVE_PATHS_H\"" >>configure.lua
+echo "#undef HAVE_PATHS_H" >config/have_paths_h.h
+echo "hdefs[\"HAVE_PATHS_H\"] = nil" >>configure.lua
+fi;
+if [ "${cache}" != "" ]; then
+	echo "$HAVE_PATHS_H" > ${cache}/ctest-HAVE_PATHS_H
+	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_PATHS_H
+fi
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
+if [ "${HAVE_PATHS_H}" = "yes" ]
+ then
+HAVE_PATHS_H="1"
+echo "#ifndef HAVE_PATHS_H" > config/have_paths_h.h
+echo "#define HAVE_PATHS_H \"$HAVE_PATHS_H\"" >> config/have_paths_h.h
+echo "#endif" >> config/have_paths_h.h
+echo "hdefs[\"HAVE_PATHS_H\"] = \"$HAVE_PATHS_H\"" >>configure.lua
+fi
+$ECHO_N "checking for <time.h>..."
+$ECHO_N "checking for <time.h>..." >> config.log
+MK_CACHED="No"
+MK_COMPILE_STATUS="OK"
+if [ "${cache}" != "" ]; then
+	if [ -e "${cache}/ctest-HAVE_TIME_H" ]; then
+		HAVE_TIME_H=`cat ${cache}/ctest-HAVE_TIME_H`
+		MK_COMPILE_STATUS=`cat ${cache}/ctest-status-HAVE_TIME_H`
+		MK_CACHED="Yes"
+	fi
+fi
+if [ "${MK_CACHED}" = "No" ]; then
+	cat << EOT > conftest.c
+#include <time.h>
+int main (int argc, char *argv[]) { return (0); }
+
+EOT
+	echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c -include sys/types.h -include sys/time.h" >>config.log
+	$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c -include sys/types.h -include sys/time.h 2>>config.log
+	if [ $? != 0 ]; then
+		echo "-> failed ($?)" >> config.log
+		MK_COMPILE_STATUS="FAIL($?)"
+	fi
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_TIME_H="yes"
+echo "HAVE_TIME_H=$HAVE_TIME_H" >>Makefile.config
+echo "mdefs[\"HAVE_TIME_H\"] = \"$HAVE_TIME_H\"" >>configure.lua
+echo "#ifndef HAVE_TIME_H" > config/have_time_h.h
+echo "#define HAVE_TIME_H \"$HAVE_TIME_H\"" >> config/have_time_h.h
+echo "#endif" >> config/have_time_h.h
+echo "hdefs[\"HAVE_TIME_H\"] = \"$HAVE_TIME_H\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE_TIME_H="no"
+echo "HAVE_TIME_H=$HAVE_TIME_H" >>Makefile.config
+echo "mdefs[\"HAVE_TIME_H\"] = \"$HAVE_TIME_H\"" >>configure.lua
+echo "#undef HAVE_TIME_H" >config/have_time_h.h
+echo "hdefs[\"HAVE_TIME_H\"] = nil" >>configure.lua
+fi;
+if [ "${cache}" != "" ]; then
+	echo "$HAVE_TIME_H" > ${cache}/ctest-HAVE_TIME_H
+	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_TIME_H
+fi
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
+if [ "${HAVE_TIME_H}" = "yes" ]
+ then
+TIME_WITH_SYS_TIME="1"
+echo "#ifndef TIME_WITH_SYS_TIME" > config/time_with_sys_time.h
+echo "#define TIME_WITH_SYS_TIME \"$TIME_WITH_SYS_TIME\"" >> config/time_with_sys_time.h
+echo "#endif" >> config/time_with_sys_time.h
+echo "hdefs[\"TIME_WITH_SYS_TIME\"] = \"$TIME_WITH_SYS_TIME\"" >>configure.lua
+    echo "This test for sys/time.h with time.h is probably not powerfull..."
 fi
 SYSLOGD_LIBS="${L_SYSLOGD_LIBS}"
 echo "SYSLOGD_LIBS=$SYSLOGD_LIBS" >>Makefile.config
