Another big thing done

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3308,14 +3308,6 @@ echo "#define HAVE_INET_ADDR $HAVE_INET_ADDR" >> config/have_inet_addr.h
 echo "#endif" >> config/have_inet_addr.h
 echo "hdefs[\"HAVE_INET_ADDR\"] = $HAVE_INET_ADDR" >>configure.lua
 fi
-$ECHO_N "plop #include <stdio.h>
-#include <sys/types.h>
-#include <sys/socket.h>
-"
-$ECHO_N "plop #include <stdio.h>
-#include <sys/types.h>
-#include <sys/socket.h>
-" >> config.log
 $ECHO_N "checking for socklen_t..."
 $ECHO_N "checking for socklen_t..." >> config.log
 MK_CACHED="No"
@@ -3380,6 +3372,390 @@ echo "#ifndef HAVE_SOCKLEN_T" > config/have_socklen_t.h
 echo "#define HAVE_SOCKLEN_T $HAVE_SOCKLEN_T" >> config/have_socklen_t.h
 echo "#endif" >> config/have_socklen_t.h
 echo "hdefs[\"HAVE_SOCKLEN_T\"] = $HAVE_SOCKLEN_T" >>configure.lua
+fi
+$ECHO_N "checking for uint32_t..."
+$ECHO_N "checking for uint32_t..." >> config.log
+MK_CACHED="No"
+MK_COMPILE_STATUS="OK"
+if [ "${cache}" != "" ]; then
+	if [ -e "${cache}/ctest-HAVE_UINT32_T" ]; then
+		HAVE_UINT32_T=`cat ${cache}/ctest-HAVE_UINT32_T`
+		MK_COMPILE_STATUS=`cat ${cache}/ctest-status-HAVE_UINT32_T`
+		MK_CACHED="Yes"
+	fi
+fi
+if [ "${MK_CACHED}" = "No" ]; then
+	cat << EOT > conftest.c
+#include <stdio.h>
+#include <sys/types.h>
+
+int
+main () {
+    if (sizeof (uint32_t))
+	return 0;
+;
+return 0;
+}
+
+EOT
+	echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+	$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+	if [ $? != 0 ]; then
+		echo "-> failed ($?)" >> config.log
+		MK_COMPILE_STATUS="FAIL($?)"
+	fi
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_UINT32_T="yes"
+echo "HAVE_UINT32_T=$HAVE_UINT32_T" >>Makefile.config
+echo "mdefs[\"HAVE_UINT32_T\"] = \"$HAVE_UINT32_T\"" >>configure.lua
+echo "#ifndef HAVE_UINT32_T" > config/have_uint32_t.h
+echo "#define HAVE_UINT32_T \"$HAVE_UINT32_T\"" >> config/have_uint32_t.h
+echo "#endif" >> config/have_uint32_t.h
+echo "hdefs[\"HAVE_UINT32_T\"] = \"$HAVE_UINT32_T\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE_UINT32_T="no"
+echo "HAVE_UINT32_T=$HAVE_UINT32_T" >>Makefile.config
+echo "mdefs[\"HAVE_UINT32_T\"] = \"$HAVE_UINT32_T\"" >>configure.lua
+echo "#undef HAVE_UINT32_T" >config/have_uint32_t.h
+echo "hdefs[\"HAVE_UINT32_T\"] = nil" >>configure.lua
+fi;
+if [ "${cache}" != "" ]; then
+	echo "$HAVE_UINT32_T" > ${cache}/ctest-HAVE_UINT32_T
+	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_UINT32_T
+fi
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
+if [ "${HAVE_UINT32_T}" = "yes" ]
+ then
+HAVE_UINT32_T="1"
+echo "#ifndef HAVE_UINT32_T" > config/have_uint32_t.h
+echo "#define HAVE_UINT32_T $HAVE_UINT32_T" >> config/have_uint32_t.h
+echo "#endif" >> config/have_uint32_t.h
+echo "hdefs[\"HAVE_UINT32_T\"] = $HAVE_UINT32_T" >>configure.lua
+fi
+$ECHO_N "checking for uint64_t..."
+$ECHO_N "checking for uint64_t..." >> config.log
+MK_CACHED="No"
+MK_COMPILE_STATUS="OK"
+if [ "${cache}" != "" ]; then
+	if [ -e "${cache}/ctest-HAVE_UINT64_T" ]; then
+		HAVE_UINT64_T=`cat ${cache}/ctest-HAVE_UINT64_T`
+		MK_COMPILE_STATUS=`cat ${cache}/ctest-status-HAVE_UINT64_T`
+		MK_CACHED="Yes"
+	fi
+fi
+if [ "${MK_CACHED}" = "No" ]; then
+	cat << EOT > conftest.c
+#include <stdio.h>
+#include <sys/types.h>
+
+int
+main () {
+    if (sizeof (uint64_t))
+	return 0;
+;
+return 0;
+}
+
+EOT
+	echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+	$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+	if [ $? != 0 ]; then
+		echo "-> failed ($?)" >> config.log
+		MK_COMPILE_STATUS="FAIL($?)"
+	fi
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_UINT64_T="yes"
+echo "HAVE_UINT64_T=$HAVE_UINT64_T" >>Makefile.config
+echo "mdefs[\"HAVE_UINT64_T\"] = \"$HAVE_UINT64_T\"" >>configure.lua
+echo "#ifndef HAVE_UINT64_T" > config/have_uint64_t.h
+echo "#define HAVE_UINT64_T \"$HAVE_UINT64_T\"" >> config/have_uint64_t.h
+echo "#endif" >> config/have_uint64_t.h
+echo "hdefs[\"HAVE_UINT64_T\"] = \"$HAVE_UINT64_T\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE_UINT64_T="no"
+echo "HAVE_UINT64_T=$HAVE_UINT64_T" >>Makefile.config
+echo "mdefs[\"HAVE_UINT64_T\"] = \"$HAVE_UINT64_T\"" >>configure.lua
+echo "#undef HAVE_UINT64_T" >config/have_uint64_t.h
+echo "hdefs[\"HAVE_UINT64_T\"] = nil" >>configure.lua
+fi;
+if [ "${cache}" != "" ]; then
+	echo "$HAVE_UINT64_T" > ${cache}/ctest-HAVE_UINT64_T
+	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_UINT64_T
+fi
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
+if [ "${HAVE_UINT64_T}" = "yes" ]
+ then
+HAVE_UINT64_T="1"
+echo "#ifndef HAVE_UINT64_T" > config/have_uint64_t.h
+echo "#define HAVE_UINT64_T $HAVE_UINT64_T" >> config/have_uint64_t.h
+echo "#endif" >> config/have_uint64_t.h
+echo "hdefs[\"HAVE_UINT64_T\"] = $HAVE_UINT64_T" >>configure.lua
+fi
+$ECHO_N "checking for u_int32_t..."
+$ECHO_N "checking for u_int32_t..." >> config.log
+MK_CACHED="No"
+MK_COMPILE_STATUS="OK"
+if [ "${cache}" != "" ]; then
+	if [ -e "${cache}/ctest-HAVE_U_INT32_T" ]; then
+		HAVE_U_INT32_T=`cat ${cache}/ctest-HAVE_U_INT32_T`
+		MK_COMPILE_STATUS=`cat ${cache}/ctest-status-HAVE_U_INT32_T`
+		MK_CACHED="Yes"
+	fi
+fi
+if [ "${MK_CACHED}" = "No" ]; then
+	cat << EOT > conftest.c
+#include <stdio.h>
+#include <sys/types.h>
+
+int
+main () {
+    if (sizeof (u_int32_t))
+	return 0;
+;
+return 0;
+}
+
+EOT
+	echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+	$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+	if [ $? != 0 ]; then
+		echo "-> failed ($?)" >> config.log
+		MK_COMPILE_STATUS="FAIL($?)"
+	fi
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_U_INT32_T="yes"
+echo "HAVE_U_INT32_T=$HAVE_U_INT32_T" >>Makefile.config
+echo "mdefs[\"HAVE_U_INT32_T\"] = \"$HAVE_U_INT32_T\"" >>configure.lua
+echo "#ifndef HAVE_U_INT32_T" > config/have_u_int32_t.h
+echo "#define HAVE_U_INT32_T \"$HAVE_U_INT32_T\"" >> config/have_u_int32_t.h
+echo "#endif" >> config/have_u_int32_t.h
+echo "hdefs[\"HAVE_U_INT32_T\"] = \"$HAVE_U_INT32_T\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE_U_INT32_T="no"
+echo "HAVE_U_INT32_T=$HAVE_U_INT32_T" >>Makefile.config
+echo "mdefs[\"HAVE_U_INT32_T\"] = \"$HAVE_U_INT32_T\"" >>configure.lua
+echo "#undef HAVE_U_INT32_T" >config/have_u_int32_t.h
+echo "hdefs[\"HAVE_U_INT32_T\"] = nil" >>configure.lua
+fi;
+if [ "${cache}" != "" ]; then
+	echo "$HAVE_U_INT32_T" > ${cache}/ctest-HAVE_U_INT32_T
+	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_U_INT32_T
+fi
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
+if [ "${HAVE_U_INT32_T}" = "yes" ]
+ then
+HAVE_U_INT32_T="1"
+echo "#ifndef HAVE_U_INT32_T" > config/have_u_int32_t.h
+echo "#define HAVE_U_INT32_T $HAVE_U_INT32_T" >> config/have_u_int32_t.h
+echo "#endif" >> config/have_u_int32_t.h
+echo "hdefs[\"HAVE_U_INT32_T\"] = $HAVE_U_INT32_T" >>configure.lua
+fi
+$ECHO_N "checking for u_int64_t..."
+$ECHO_N "checking for u_int64_t..." >> config.log
+MK_CACHED="No"
+MK_COMPILE_STATUS="OK"
+if [ "${cache}" != "" ]; then
+	if [ -e "${cache}/ctest-HAVE_U_INT64_T" ]; then
+		HAVE_U_INT64_T=`cat ${cache}/ctest-HAVE_U_INT64_T`
+		MK_COMPILE_STATUS=`cat ${cache}/ctest-status-HAVE_U_INT64_T`
+		MK_CACHED="Yes"
+	fi
+fi
+if [ "${MK_CACHED}" = "No" ]; then
+	cat << EOT > conftest.c
+#include <stdio.h>
+#include <sys/types.h>
+
+int
+main () {
+    if (sizeof (u_int64_t))
+	return 0;
+;
+return 0;
+}
+
+EOT
+	echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+	$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+	if [ $? != 0 ]; then
+		echo "-> failed ($?)" >> config.log
+		MK_COMPILE_STATUS="FAIL($?)"
+	fi
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_U_INT64_T="yes"
+echo "HAVE_U_INT64_T=$HAVE_U_INT64_T" >>Makefile.config
+echo "mdefs[\"HAVE_U_INT64_T\"] = \"$HAVE_U_INT64_T\"" >>configure.lua
+echo "#ifndef HAVE_U_INT64_T" > config/have_u_int64_t.h
+echo "#define HAVE_U_INT64_T \"$HAVE_U_INT64_T\"" >> config/have_u_int64_t.h
+echo "#endif" >> config/have_u_int64_t.h
+echo "hdefs[\"HAVE_U_INT64_T\"] = \"$HAVE_U_INT64_T\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE_U_INT64_T="no"
+echo "HAVE_U_INT64_T=$HAVE_U_INT64_T" >>Makefile.config
+echo "mdefs[\"HAVE_U_INT64_T\"] = \"$HAVE_U_INT64_T\"" >>configure.lua
+echo "#undef HAVE_U_INT64_T" >config/have_u_int64_t.h
+echo "hdefs[\"HAVE_U_INT64_T\"] = nil" >>configure.lua
+fi;
+if [ "${cache}" != "" ]; then
+	echo "$HAVE_U_INT64_T" > ${cache}/ctest-HAVE_U_INT64_T
+	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_U_INT64_T
+fi
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
+if [ "${HAVE_U_INT64_T}" = "yes" ]
+ then
+HAVE_U_INT64_T="1"
+echo "#ifndef HAVE_U_INT64_T" > config/have_u_int64_t.h
+echo "#define HAVE_U_INT64_T $HAVE_U_INT64_T" >> config/have_u_int64_t.h
+echo "#endif" >> config/have_u_int64_t.h
+echo "hdefs[\"HAVE_U_INT64_T\"] = $HAVE_U_INT64_T" >>configure.lua
+fi
+$ECHO_N "checking for __uint32_t..."
+$ECHO_N "checking for __uint32_t..." >> config.log
+MK_CACHED="No"
+MK_COMPILE_STATUS="OK"
+if [ "${cache}" != "" ]; then
+	if [ -e "${cache}/ctest-HAVE___UINT32_T" ]; then
+		HAVE___UINT32_T=`cat ${cache}/ctest-HAVE___UINT32_T`
+		MK_COMPILE_STATUS=`cat ${cache}/ctest-status-HAVE___UINT32_T`
+		MK_CACHED="Yes"
+	fi
+fi
+if [ "${MK_CACHED}" = "No" ]; then
+	cat << EOT > conftest.c
+#include <stdio.h>
+#include <sys/types.h>
+
+int
+main () {
+    if (sizeof (__uint32_t))
+	return 0;
+;
+return 0;
+}
+
+EOT
+	echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+	$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+	if [ $? != 0 ]; then
+		echo "-> failed ($?)" >> config.log
+		MK_COMPILE_STATUS="FAIL($?)"
+	fi
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE___UINT32_T="yes"
+echo "HAVE___UINT32_T=$HAVE___UINT32_T" >>Makefile.config
+echo "mdefs[\"HAVE___UINT32_T\"] = \"$HAVE___UINT32_T\"" >>configure.lua
+echo "#ifndef HAVE___UINT32_T" > config/have___uint32_t.h
+echo "#define HAVE___UINT32_T \"$HAVE___UINT32_T\"" >> config/have___uint32_t.h
+echo "#endif" >> config/have___uint32_t.h
+echo "hdefs[\"HAVE___UINT32_T\"] = \"$HAVE___UINT32_T\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE___UINT32_T="no"
+echo "HAVE___UINT32_T=$HAVE___UINT32_T" >>Makefile.config
+echo "mdefs[\"HAVE___UINT32_T\"] = \"$HAVE___UINT32_T\"" >>configure.lua
+echo "#undef HAVE___UINT32_T" >config/have___uint32_t.h
+echo "hdefs[\"HAVE___UINT32_T\"] = nil" >>configure.lua
+fi;
+if [ "${cache}" != "" ]; then
+	echo "$HAVE___UINT32_T" > ${cache}/ctest-HAVE___UINT32_T
+	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE___UINT32_T
+fi
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
+if [ "${HAVE___UINT32_T}" = "yes" ]
+ then
+HAVE___UINT32_T="1"
+echo "#ifndef HAVE___UINT32_T" > config/have___uint32_t.h
+echo "#define HAVE___UINT32_T $HAVE___UINT32_T" >> config/have___uint32_t.h
+echo "#endif" >> config/have___uint32_t.h
+echo "hdefs[\"HAVE___UINT32_T\"] = $HAVE___UINT32_T" >>configure.lua
+fi
+$ECHO_N "checking for __uint64_t..."
+$ECHO_N "checking for __uint64_t..." >> config.log
+MK_CACHED="No"
+MK_COMPILE_STATUS="OK"
+if [ "${cache}" != "" ]; then
+	if [ -e "${cache}/ctest-HAVE___UINT64_T" ]; then
+		HAVE___UINT64_T=`cat ${cache}/ctest-HAVE___UINT64_T`
+		MK_COMPILE_STATUS=`cat ${cache}/ctest-status-HAVE___UINT64_T`
+		MK_CACHED="Yes"
+	fi
+fi
+if [ "${MK_CACHED}" = "No" ]; then
+	cat << EOT > conftest.c
+#include <stdio.h>
+#include <sys/types.h>
+
+int
+main () {
+    if (sizeof (__uint64_t))
+	return 0;
+;
+return 0;
+}
+
+EOT
+	echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+	$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+	if [ $? != 0 ]; then
+		echo "-> failed ($?)" >> config.log
+		MK_COMPILE_STATUS="FAIL($?)"
+	fi
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE___UINT64_T="yes"
+echo "HAVE___UINT64_T=$HAVE___UINT64_T" >>Makefile.config
+echo "mdefs[\"HAVE___UINT64_T\"] = \"$HAVE___UINT64_T\"" >>configure.lua
+echo "#ifndef HAVE___UINT64_T" > config/have___uint64_t.h
+echo "#define HAVE___UINT64_T \"$HAVE___UINT64_T\"" >> config/have___uint64_t.h
+echo "#endif" >> config/have___uint64_t.h
+echo "hdefs[\"HAVE___UINT64_T\"] = \"$HAVE___UINT64_T\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE___UINT64_T="no"
+echo "HAVE___UINT64_T=$HAVE___UINT64_T" >>Makefile.config
+echo "mdefs[\"HAVE___UINT64_T\"] = \"$HAVE___UINT64_T\"" >>configure.lua
+echo "#undef HAVE___UINT64_T" >config/have___uint64_t.h
+echo "hdefs[\"HAVE___UINT64_T\"] = nil" >>configure.lua
+fi;
+if [ "${cache}" != "" ]; then
+	echo "$HAVE___UINT64_T" > ${cache}/ctest-HAVE___UINT64_T
+	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE___UINT64_T
+fi
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
+if [ "${HAVE___UINT64_T}" = "yes" ]
+ then
+HAVE___UINT64_T="1"
+echo "#ifndef HAVE___UINT64_T" > config/have___uint64_t.h
+echo "#define HAVE___UINT64_T $HAVE___UINT64_T" >> config/have___uint64_t.h
+echo "#endif" >> config/have___uint64_t.h
+echo "hdefs[\"HAVE___UINT64_T\"] = $HAVE___UINT64_T" >>configure.lua
 fi
 SYSLOGD_LIBS="${L_SYSLOGD_LIBS}"
 echo "SYSLOGD_LIBS=$SYSLOGD_LIBS" >>Makefile.config
