Update to use HDEFINE_UNQUOTED, but, GENERATING CONFIGURE is only with BSDBUILD trunk with my patchs for the moment (UNQUOTED and CHECK_FUNC).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1816,9 +1816,9 @@ if test "${UNAME}" = "OpenBSD"
  then
 DLOPEN_FLAGS="RTLD_LAZY"
 echo "#ifndef DLOPEN_FLAGS" > config/dlopen_flags.h
-echo "#define DLOPEN_FLAGS \"$DLOPEN_FLAGS\"" >> config/dlopen_flags.h
+echo "#define DLOPEN_FLAGS $DLOPEN_FLAGS" >> config/dlopen_flags.h
 echo "#endif" >> config/dlopen_flags.h
-echo "hdefs[\"DLOPEN_FLAGS\"] = \"$DLOPEN_FLAGS\"" >>configure.lua
+echo "hdefs[\"DLOPEN_FLAGS\"] = $DLOPEN_FLAGS" >>configure.lua
 SYMBOL_PREFIX="_"
 echo "#ifndef SYMBOL_PREFIX" > config/symbol_prefix.h
 echo "#define SYMBOL_PREFIX \"$SYMBOL_PREFIX\"" >> config/symbol_prefix.h
@@ -1835,9 +1835,9 @@ elif test "${UNAME}" = "FreeBSD"
  then
 DLOPEN_FLAGS="RTLD_LAZY"
 echo "#ifndef DLOPEN_FLAGS" > config/dlopen_flags.h
-echo "#define DLOPEN_FLAGS \"$DLOPEN_FLAGS\"" >> config/dlopen_flags.h
+echo "#define DLOPEN_FLAGS $DLOPEN_FLAGS" >> config/dlopen_flags.h
 echo "#endif" >> config/dlopen_flags.h
-echo "hdefs[\"DLOPEN_FLAGS\"] = \"$DLOPEN_FLAGS\"" >>configure.lua
+echo "hdefs[\"DLOPEN_FLAGS\"] = $DLOPEN_FLAGS" >>configure.lua
 SYMBOL_PREFIX=""
 echo "#ifndef SYMBOL_PREFIX" > config/symbol_prefix.h
 echo "#define SYMBOL_PREFIX \"$SYMBOL_PREFIX\"" >> config/symbol_prefix.h
@@ -1855,9 +1855,9 @@ elif test "${UNAME}" = "NetBSD"
  then
 DLOPEN_FLAGS="RTLD_LAZY"
 echo "#ifndef DLOPEN_FLAGS" > config/dlopen_flags.h
-echo "#define DLOPEN_FLAGS \"$DLOPEN_FLAGS\"" >> config/dlopen_flags.h
+echo "#define DLOPEN_FLAGS $DLOPEN_FLAGS" >> config/dlopen_flags.h
 echo "#endif" >> config/dlopen_flags.h
-echo "hdefs[\"DLOPEN_FLAGS\"] = \"$DLOPEN_FLAGS\"" >>configure.lua
+echo "hdefs[\"DLOPEN_FLAGS\"] = $DLOPEN_FLAGS" >>configure.lua
 SYMBOL_PREFIX=""
 echo "#ifndef SYMBOL_PREFIX" > config/symbol_prefix.h
 echo "#define SYMBOL_PREFIX \"$SYMBOL_PREFIX\"" >> config/symbol_prefix.h
@@ -1875,9 +1875,9 @@ elif test "${UNAME}" = "Linux"
  then
 DLOPEN_FLAGS="RTLD_LAZY | RTLD_GLOBAL"
 echo "#ifndef DLOPEN_FLAGS" > config/dlopen_flags.h
-echo "#define DLOPEN_FLAGS \"$DLOPEN_FLAGS\"" >> config/dlopen_flags.h
+echo "#define DLOPEN_FLAGS $DLOPEN_FLAGS" >> config/dlopen_flags.h
 echo "#endif" >> config/dlopen_flags.h
-echo "hdefs[\"DLOPEN_FLAGS\"] = \"$DLOPEN_FLAGS\"" >>configure.lua
+echo "hdefs[\"DLOPEN_FLAGS\"] = $DLOPEN_FLAGS" >>configure.lua
 SYMBOL_PREFIX=""
 echo "#ifndef SYMBOL_PREFIX" > config/symbol_prefix.h
 echo "#define SYMBOL_PREFIX \"$SYMBOL_PREFIX\"" >> config/symbol_prefix.h
@@ -1897,14 +1897,14 @@ elif test "${UNAME}" = "SunOS"
  then
 DLOPEN_FLAGS="RTLD_LAZY"
 echo "#ifndef DLOPEN_FLAGS" > config/dlopen_flags.h
-echo "#define DLOPEN_FLAGS \"$DLOPEN_FLAGS\"" >> config/dlopen_flags.h
+echo "#define DLOPEN_FLAGS $DLOPEN_FLAGS" >> config/dlopen_flags.h
 echo "#endif" >> config/dlopen_flags.h
-echo "hdefs[\"DLOPEN_FLAGS\"] = \"$DLOPEN_FLAGS\"" >>configure.lua
+echo "hdefs[\"DLOPEN_FLAGS\"] = $DLOPEN_FLAGS" >>configure.lua
 _REENTRANT="1"
 echo "#ifndef _REENTRANT" > config/_reentrant.h
-echo "#define _REENTRANT \"$_REENTRANT\"" >> config/_reentrant.h
+echo "#define _REENTRANT $_REENTRANT" >> config/_reentrant.h
 echo "#endif" >> config/_reentrant.h
-echo "hdefs[\"_REENTRANT\"] = \"$_REENTRANT\"" >>configure.lua
+echo "hdefs[\"_REENTRANT\"] = $_REENTRANT" >>configure.lua
 SYMBOL_PREFIX=""
 echo "#ifndef SYMBOL_PREFIX" > config/symbol_prefix.h
 echo "#define SYMBOL_PREFIX \"$SYMBOL_PREFIX\"" >> config/symbol_prefix.h
@@ -1931,14 +1931,14 @@ elif test "${UNAME}" = "AIX"
  then
 DLOPEN_FLAGS="RTLD_LAZY | RTLD_GLOBAL"
 echo "#ifndef DLOPEN_FLAGS" > config/dlopen_flags.h
-echo "#define DLOPEN_FLAGS \"$DLOPEN_FLAGS\"" >> config/dlopen_flags.h
+echo "#define DLOPEN_FLAGS $DLOPEN_FLAGS" >> config/dlopen_flags.h
 echo "#endif" >> config/dlopen_flags.h
-echo "hdefs[\"DLOPEN_FLAGS\"] = \"$DLOPEN_FLAGS\"" >>configure.lua
+echo "hdefs[\"DLOPEN_FLAGS\"] = $DLOPEN_FLAGS" >>configure.lua
 NEEDS_DLOPEN_NULL="1"
 echo "#ifndef NEEDS_DLOPEN_NULL" > config/needs_dlopen_null.h
-echo "#define NEEDS_DLOPEN_NULL \"$NEEDS_DLOPEN_NULL\"" >> config/needs_dlopen_null.h
+echo "#define NEEDS_DLOPEN_NULL $NEEDS_DLOPEN_NULL" >> config/needs_dlopen_null.h
 echo "#endif" >> config/needs_dlopen_null.h
-echo "hdefs[\"NEEDS_DLOPEN_NULL\"] = \"$NEEDS_DLOPEN_NULL\"" >>configure.lua
+echo "hdefs[\"NEEDS_DLOPEN_NULL\"] = $NEEDS_DLOPEN_NULL" >>configure.lua
 SYMBOL_PREFIX=""
 echo "#ifndef SYMBOL_PREFIX" > config/symbol_prefix.h
 echo "#define SYMBOL_PREFIX \"$SYMBOL_PREFIX\"" >> config/symbol_prefix.h
@@ -1970,9 +1970,9 @@ echo "#endif" >> config/symbol_prefix.h
 echo "hdefs[\"SYMBOL_PREFIX\"] = \"$SYMBOL_PREFIX\"" >>configure.lua
 DLOPEN_FLAGS="RTLD_LAZY"
 echo "#ifndef DLOPEN_FLAGS" > config/dlopen_flags.h
-echo "#define DLOPEN_FLAGS \"$DLOPEN_FLAGS\"" >> config/dlopen_flags.h
+echo "#define DLOPEN_FLAGS $DLOPEN_FLAGS" >> config/dlopen_flags.h
 echo "#endif" >> config/dlopen_flags.h
-echo "hdefs[\"DLOPEN_FLAGS\"] = \"$DLOPEN_FLAGS\"" >>configure.lua
+echo "hdefs[\"DLOPEN_FLAGS\"] = $DLOPEN_FLAGS" >>configure.lua
 SHARED_PARAMS="-Bshareable"
 echo "SHARED_PARAMS=$SHARED_PARAMS" >>Makefile.config
 echo "mdefs[\"SHARED_PARAMS\"] = \"$SHARED_PARAMS\"" >>configure.lua
@@ -1987,11 +1987,11 @@ echo "hdefs[\"SY_DEBUG\"] = \"$SY_DEBUG\"" >>configure.lua
 DEBUG_FLAGS="-g -ggdb3 -fno-inline"
 echo "DEBUG_FLAGS=$DEBUG_FLAGS" >>Makefile.config
 echo "mdefs[\"DEBUG_FLAGS\"] = \"$DEBUG_FLAGS\"" >>configure.lua
-    END_WITH_DEBUG="yes"
+    want_debug=yes
 else
 echo "#undef SY_DEBUG" >config/sy_debug.h
 echo "hdefs[\"SY_DEBUG\"] = nil" >>configure.lua
-    END_WITH_DEBUG="no"
+    want_debug=no
 fi
 temp_res="no"
 if test "$UNAME" = "OpenBSD" -o "$UNAME" = "NetBSD"	\
@@ -2007,9 +2007,9 @@ if [ "${temp_res}" = "yes" ]
     MANPAGES8="${MANPAGES8} im_bsd.8"
 HAVE_BSD_IMODULE="1"
 echo "#ifndef HAVE_BSD_IMODULE" > config/have_bsd_imodule.h
-echo "#define HAVE_BSD_IMODULE \"$HAVE_BSD_IMODULE\"" >> config/have_bsd_imodule.h
+echo "#define HAVE_BSD_IMODULE $HAVE_BSD_IMODULE" >> config/have_bsd_imodule.h
 echo "#endif" >> config/have_bsd_imodule.h
-echo "hdefs[\"HAVE_BSD_IMODULE\"] = \"$HAVE_BSD_IMODULE\"" >>configure.lua
+echo "hdefs[\"HAVE_BSD_IMODULE\"] = $HAVE_BSD_IMODULE" >>configure.lua
     want_bsd=yes
 else
     want_bsd=no
@@ -2075,9 +2075,9 @@ rm -f conftest.c $testdir/conftest$EXECSUFFIX
 	MANPAGES8="${MANPAGES8} im_linux.8"
 HAVE_LINUX_IMODULE="1"
 echo "#ifndef HAVE_LINUX_IMODULE" > config/have_linux_imodule.h
-echo "#define HAVE_LINUX_IMODULE \"$HAVE_LINUX_IMODULE\"" >> config/have_linux_imodule.h
+echo "#define HAVE_LINUX_IMODULE $HAVE_LINUX_IMODULE" >> config/have_linux_imodule.h
 echo "#endif" >> config/have_linux_imodule.h
-echo "hdefs[\"HAVE_LINUX_IMODULE\"] = \"$HAVE_LINUX_IMODULE\"" >>configure.lua
+echo "hdefs[\"HAVE_LINUX_IMODULE\"] = $HAVE_LINUX_IMODULE" >>configure.lua
 	want_linux=yes
     else
 	exit 1
@@ -2145,9 +2145,9 @@ rm -f conftest.c $testdir/conftest$EXECSUFFIX
 	MANPAGES8="${MANPAGES8} im_udp.8 om_udp.8"
 HAVE_UDP_IMODULE="1"
 echo "#ifndef HAVE_UDP_IMODULE" > config/have_udp_imodule.h
-echo "#define HAVE_UDP_IMODULE \"$HAVE_UDP_IMODULE\"" >> config/have_udp_imodule.h
+echo "#define HAVE_UDP_IMODULE $HAVE_UDP_IMODULE" >> config/have_udp_imodule.h
 echo "#endif" >> config/have_udp_imodule.h
-echo "hdefs[\"HAVE_UDP_IMODULE\"] = \"$HAVE_UDP_IMODULE\"" >>configure.lua
+echo "hdefs[\"HAVE_UDP_IMODULE\"] = $HAVE_UDP_IMODULE" >>configure.lua
 	want_udp=yes
     else
 	want_udp=no
@@ -2211,9 +2211,9 @@ rm -f conftest.c $testdir/conftest$EXECSUFFIX
 	MANPAGES8="${MANPAGES8} im_unix.c"
 HAVE_UNIX_IMODULE="1"
 echo "#ifndef HAVE_UNIX_IMODULE" > config/have_unix_imodule.h
-echo "#define HAVE_UNIX_IMODULE \"$HAVE_UNIX_IMODULE\"" >> config/have_unix_imodule.h
+echo "#define HAVE_UNIX_IMODULE $HAVE_UNIX_IMODULE" >> config/have_unix_imodule.h
 echo "#endif" >> config/have_unix_imodule.h
-echo "hdefs[\"HAVE_UNIX_IMODULE\"] = \"$HAVE_UNIX_IMODULE\"" >>configure.lua
+echo "hdefs[\"HAVE_UNIX_IMODULE\"] = $HAVE_UNIX_IMODULE" >>configure.lua
 	want_unix=yes
     else
 	want_unix=no
@@ -2333,9 +2333,9 @@ if test "$temp_res" = "yes"
     SYSLOGD_LIBS="${SYSLOGD_LIBS} -lthread -ldoor"
 HAVE_STREAMS_IMODULE="1"
 echo "#ifndef HAVE_STREAMS_IMODULE" > config/have_streams_imodule.h
-echo "#define HAVE_STREAMS_IMODULE \"$HAVE_STREAMS_IMODULE\"" >> config/have_streams_imodule.h
+echo "#define HAVE_STREAMS_IMODULE $HAVE_STREAMS_IMODULE" >> config/have_streams_imodule.h
 echo "#endif" >> config/have_streams_imodule.h
-echo "hdefs[\"HAVE_STREAMS_IMODULE\"] = \"$HAVE_STREAMS_IMODULE\"" >>configure.lua
+echo "hdefs[\"HAVE_STREAMS_IMODULE\"] = $HAVE_STREAMS_IMODULE" >>configure.lua
     want_streams=yes
 else
     want_streams=no
@@ -2349,9 +2349,9 @@ else
     MANPAGES8="${MANPAGES8} om_classic.8"
 HAVE_CLASSIC_IMODULE="1"
 echo "#ifndef HAVE_CLASSIC_IMODULE" > config/have_classic_imodule.h
-echo "#define HAVE_CLASSIC_IMODULE \"$HAVE_CLASSIC_IMODULE\"" >> config/have_classic_imodule.h
+echo "#define HAVE_CLASSIC_IMODULE $HAVE_CLASSIC_IMODULE" >> config/have_classic_imodule.h
 echo "#endif" >> config/have_classic_imodule.h
-echo "hdefs[\"HAVE_CLASSIC_IMODULE\"] = \"$HAVE_CLASSIC_IMODULE\"" >>configure.lua
+echo "hdefs[\"HAVE_CLASSIC_IMODULE\"] = $HAVE_CLASSIC_IMODULE" >>configure.lua
     want_classic=yes
 fi
 if [ "${enable_tcp}" = "no" ]
@@ -2412,9 +2412,9 @@ rm -f conftest.c $testdir/conftest$EXECSUFFIX
     	MANPAGES8="${MANPAGES8} om_tcp.8 im_tcp.8"
 HAVE_TCP_IMODULE="1"
 echo "#ifndef HAVE_TCP_IMODULE" > config/have_tcp_imodule.h
-echo "#define HAVE_TCP_IMODULE \"$HAVE_TCP_IMODULE\"" >> config/have_tcp_imodule.h
+echo "#define HAVE_TCP_IMODULE $HAVE_TCP_IMODULE" >> config/have_tcp_imodule.h
 echo "#endif" >> config/have_tcp_imodule.h
-echo "hdefs[\"HAVE_TCP_IMODULE\"] = \"$HAVE_TCP_IMODULE\"" >>configure.lua
+echo "hdefs[\"HAVE_TCP_IMODULE\"] = $HAVE_TCP_IMODULE" >>configure.lua
     	want_tcp=yes
     else
 	want_tcp=no
@@ -2430,9 +2430,9 @@ else
     MANPAGES8="${MANPAGES8} om_oracle8i.8"
 HAVE_ORACLE8I_IMODULE="1"
 echo "#ifndef HAVE_ORACLE8I_IMODULE" > config/have_oracle8i_imodule.h
-echo "#define HAVE_ORACLE8I_IMODULE \"$HAVE_ORACLE8I_IMODULE\"" >> config/have_oracle8i_imodule.h
+echo "#define HAVE_ORACLE8I_IMODULE $HAVE_ORACLE8I_IMODULE" >> config/have_oracle8i_imodule.h
 echo "#endif" >> config/have_oracle8i_imodule.h
-echo "hdefs[\"HAVE_ORACLE8I_IMODULE\"] = \"$HAVE_ORACLE8I_IMODULE\"" >>configure.lua
+echo "hdefs[\"HAVE_ORACLE8I_IMODULE\"] = $HAVE_ORACLE8I_IMODULE" >>configure.lua
     USE_SQL="yes"
 fi
 if [ "${enable_mysql}" = "no" ]
@@ -2443,9 +2443,9 @@ else
     MANPAGES8="${MANPAGES8} om_mysql.8"
 HAVE_MYSQL_IMODULE="1"
 echo "#ifndef HAVE_MYSQL_IMODULE" > config/have_mysql_imodule.h
-echo "#define HAVE_MYSQL_IMODULE \"$HAVE_MYSQL_IMODULE\"" >> config/have_mysql_imodule.h
+echo "#define HAVE_MYSQL_IMODULE $HAVE_MYSQL_IMODULE" >> config/have_mysql_imodule.h
 echo "#endif" >> config/have_mysql_imodule.h
-echo "hdefs[\"HAVE_MYSQL_IMODULE\"] = \"$HAVE_MYSQL_IMODULE\"" >>configure.lua
+echo "hdefs[\"HAVE_MYSQL_IMODULE\"] = $HAVE_MYSQL_IMODULE" >>configure.lua
     USE_SQL="yes"
     want_mysql=yes
 fi
@@ -2457,9 +2457,9 @@ else
     MANPAGES8="${MANPAGES8} om_pgsql.8"
 HAVE_PGSQL_IMODULE="1"
 echo "#ifndef HAVE_PGSQL_IMODULE" > config/have_pgsql_imodule.h
-echo "#define HAVE_PGSQL_IMODULE \"$HAVE_PGSQL_IMODULE\"" >> config/have_pgsql_imodule.h
+echo "#define HAVE_PGSQL_IMODULE $HAVE_PGSQL_IMODULE" >> config/have_pgsql_imodule.h
 echo "#endif" >> config/have_pgsql_imodule.h
-echo "hdefs[\"HAVE_PGSQL_IMODULE\"] = \"$HAVE_PGSQL_IMODULE\"" >>configure.lua
+echo "hdefs[\"HAVE_PGSQL_IMODULE\"] = $HAVE_PGSQL_IMODULE" >>configure.lua
     USE_SQL="yes"
     want_pgsql=yes
 fi
@@ -2657,9 +2657,9 @@ rm -f conftest.c $testdir/conftest$EXECSUFFIX
  then
 HAVE_SRANDOM="1"
 echo "#ifndef HAVE_SRANDOM" > config/have_srandom.h
-echo "#define HAVE_SRANDOM \"$HAVE_SRANDOM\"" >> config/have_srandom.h
+echo "#define HAVE_SRANDOM $HAVE_SRANDOM" >> config/have_srandom.h
 echo "#endif" >> config/have_srandom.h
-echo "hdefs[\"HAVE_SRANDOM\"] = \"$HAVE_SRANDOM\"" >>configure.lua
+echo "hdefs[\"HAVE_SRANDOM\"] = $HAVE_SRANDOM" >>configure.lua
     fi
     want_peo=yes
 else
@@ -2717,9 +2717,9 @@ if [ "${HAVE_SYSLOG_H}" = "yes" ]
  then
 HAVE_CODE="1"
 echo "#ifndef HAVE_CODE" > config/have_code.h
-echo "#define HAVE_CODE \"$HAVE_CODE\"" >> config/have_code.h
+echo "#define HAVE_CODE $HAVE_CODE" >> config/have_code.h
 echo "#endif" >> config/have_code.h
-echo "hdefs[\"HAVE_CODE\"] = \"$HAVE_CODE\"" >>configure.lua
+echo "hdefs[\"HAVE_CODE\"] = $HAVE_CODE" >>configure.lua
 fi
 $ECHO_N "checking for <paths.h> (HAVE_PATHS_H)..."
 $ECHO_N "checking for <paths.h> (HAVE_PATHS_H)..." >> config.log
@@ -2773,9 +2773,9 @@ if [ "${HAVE_PATHS_H}" = "yes" ]
  then
 HAVE_PATHS_H="1"
 echo "#ifndef HAVE_PATHS_H" > config/have_paths_h.h
-echo "#define HAVE_PATHS_H \"$HAVE_PATHS_H\"" >> config/have_paths_h.h
+echo "#define HAVE_PATHS_H $HAVE_PATHS_H" >> config/have_paths_h.h
 echo "#endif" >> config/have_paths_h.h
-echo "hdefs[\"HAVE_PATHS_H\"] = \"$HAVE_PATHS_H\"" >>configure.lua
+echo "hdefs[\"HAVE_PATHS_H\"] = $HAVE_PATHS_H" >>configure.lua
 fi
 $ECHO_N "checking for <time.h>..."
 $ECHO_N "checking for <time.h>..." >> config.log
@@ -2829,10 +2829,164 @@ if [ "${HAVE_TIME_H}" = "yes" ]
  then
 TIME_WITH_SYS_TIME="1"
 echo "#ifndef TIME_WITH_SYS_TIME" > config/time_with_sys_time.h
-echo "#define TIME_WITH_SYS_TIME \"$TIME_WITH_SYS_TIME\"" >> config/time_with_sys_time.h
+echo "#define TIME_WITH_SYS_TIME $TIME_WITH_SYS_TIME" >> config/time_with_sys_time.h
 echo "#endif" >> config/time_with_sys_time.h
-echo "hdefs[\"TIME_WITH_SYS_TIME\"] = \"$TIME_WITH_SYS_TIME\"" >>configure.lua
+echo "hdefs[\"TIME_WITH_SYS_TIME\"] = $TIME_WITH_SYS_TIME" >>configure.lua
     echo "This test for sys/time.h with time.h is probably not powerfull..."
+fi
+$ECHO_N "checking for vprintf..."
+$ECHO_N "checking for vprintf..." >> config.log
+TEST_CFLAGS="-Wall"
+MK_CACHED="No"
+MK_COMPILE_STATUS="OK"
+if [ "${cache}" != "" ]; then
+	if [ -e "${cache}/ctest-HAVE_VPRINTF" ]; then
+		HAVE_VPRINTF=`cat ${cache}/ctest-HAVE_VPRINTF`
+		MK_COMPILE_STATUS=`cat ${cache}/ctest-status-HAVE_VPRINTF`
+		MK_CACHED="Yes"
+	fi
+fi
+if [ "${MK_CACHED}" = "No" ]; then
+	cat << EOT > conftest.c
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef vprintf
+
+#ifdef __cplusplus
+extern "C"
+#endif
+
+char vprintf();
+#if defined __stub_vprintf || defined __stub___vprintf
+choke me
+#endif
+
+int main() {
+    return vprintf();
+    ;
+    return 0;
+}
+
+EOT
+	echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+	$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+	if [ $? != 0 ]; then
+		echo "-> failed ($?)" >> config.log
+		MK_COMPILE_STATUS="FAIL($?)"
+	fi
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_VPRINTF="yes"
+echo "HAVE_VPRINTF=$HAVE_VPRINTF" >>Makefile.config
+echo "mdefs[\"HAVE_VPRINTF\"] = \"$HAVE_VPRINTF\"" >>configure.lua
+echo "#ifndef HAVE_VPRINTF" > config/have_vprintf.h
+echo "#define HAVE_VPRINTF \"$HAVE_VPRINTF\"" >> config/have_vprintf.h
+echo "#endif" >> config/have_vprintf.h
+echo "hdefs[\"HAVE_VPRINTF\"] = \"$HAVE_VPRINTF\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE_VPRINTF="no"
+echo "HAVE_VPRINTF=$HAVE_VPRINTF" >>Makefile.config
+echo "mdefs[\"HAVE_VPRINTF\"] = \"$HAVE_VPRINTF\"" >>configure.lua
+echo "#undef HAVE_VPRINTF" >config/have_vprintf.h
+echo "hdefs[\"HAVE_VPRINTF\"] = nil" >>configure.lua
+fi;
+if [ "${cache}" != "" ]; then
+	echo "$HAVE_VPRINTF" > ${cache}/ctest-HAVE_VPRINTF
+	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_VPRINTF
+fi
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
+if [ "${HAVE_VPRINTF}" = "yes" ]
+ then
+HAVE_VPRINTF="1"
+echo "#ifndef HAVE_VPRINTF" > config/have_vprintf.h
+echo "#define HAVE_VPRINTF $HAVE_VPRINTF" >> config/have_vprintf.h
+echo "#endif" >> config/have_vprintf.h
+echo "hdefs[\"HAVE_VPRINTF\"] = $HAVE_VPRINTF" >>configure.lua
+fi
+$ECHO_N "checking for _doprnt..."
+$ECHO_N "checking for _doprnt..." >> config.log
+TEST_CFLAGS="-Wall"
+MK_CACHED="No"
+MK_COMPILE_STATUS="OK"
+if [ "${cache}" != "" ]; then
+	if [ -e "${cache}/ctest-HAVE__DOPRNT" ]; then
+		HAVE__DOPRNT=`cat ${cache}/ctest-HAVE__DOPRNT`
+		MK_COMPILE_STATUS=`cat ${cache}/ctest-status-HAVE__DOPRNT`
+		MK_CACHED="Yes"
+	fi
+fi
+if [ "${MK_CACHED}" = "No" ]; then
+	cat << EOT > conftest.c
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef _doprnt
+
+#ifdef __cplusplus
+extern "C"
+#endif
+
+char _doprnt();
+#if defined __stub__doprnt || defined __stub____doprnt
+choke me
+#endif
+
+int main() {
+    return _doprnt();
+    ;
+    return 0;
+}
+
+EOT
+	echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+	$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+	if [ $? != 0 ]; then
+		echo "-> failed ($?)" >> config.log
+		MK_COMPILE_STATUS="FAIL($?)"
+	fi
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE__DOPRNT="yes"
+echo "HAVE__DOPRNT=$HAVE__DOPRNT" >>Makefile.config
+echo "mdefs[\"HAVE__DOPRNT\"] = \"$HAVE__DOPRNT\"" >>configure.lua
+echo "#ifndef HAVE__DOPRNT" > config/have__doprnt.h
+echo "#define HAVE__DOPRNT \"$HAVE__DOPRNT\"" >> config/have__doprnt.h
+echo "#endif" >> config/have__doprnt.h
+echo "hdefs[\"HAVE__DOPRNT\"] = \"$HAVE__DOPRNT\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE__DOPRNT="no"
+echo "HAVE__DOPRNT=$HAVE__DOPRNT" >>Makefile.config
+echo "mdefs[\"HAVE__DOPRNT\"] = \"$HAVE__DOPRNT\"" >>configure.lua
+echo "#undef HAVE__DOPRNT" >config/have__doprnt.h
+echo "hdefs[\"HAVE__DOPRNT\"] = nil" >>configure.lua
+fi;
+if [ "${cache}" != "" ]; then
+	echo "$HAVE__DOPRNT" > ${cache}/ctest-HAVE__DOPRNT
+	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE__DOPRNT
+fi
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
+if [ "${HAVE__DOPRNT}" = "yes" ]
+ then
+HAVE__DOPRNT="1"
+echo "#ifndef HAVE__DOPRNT" > config/have__doprnt.h
+echo "#define HAVE__DOPRNT $HAVE__DOPRNT" >> config/have__doprnt.h
+echo "#endif" >> config/have__doprnt.h
+echo "hdefs[\"HAVE__DOPRNT\"] = $HAVE__DOPRNT" >>configure.lua
 fi
 SYSLOGD_LIBS="${L_SYSLOGD_LIBS}"
 echo "SYSLOGD_LIBS=$SYSLOGD_LIBS" >>Makefile.config
@@ -2862,7 +3016,7 @@ echo "      Prefix: ${PREFIX}"
 echo "          CC: ${CC}"
 echo
 echo "Build with:"
-echo "      Debug: ${END_WITH_DEBUG}"
+echo "      Debug: ${want_debug}"
 echo "      Modules:"
 echo "          bsd: ${want_bsd}"
 echo "        linux: ${want_linux}"
