Update to syncronize with v1.08e

diff --git a/packaging/Makefile.in b/packaging/Makefile.in
--- a/packaging/Makefile.in
+++ b/packaging/Makefile.in
@@ -1,6 +1,6 @@
-# $CoreSDI: Makefile.in,v 1.25 2002/03/01 07:31:03 alejo Exp $
+# $CoreSDI: Makefile.in,v 1.9 2002/02/19 22:40:58 alejo Exp $
 #
-# Copyright (c) 2001, Core SDI S.A., Argentina
+# Copyright (c) 2001, 2002, Core SDI S.A., Argentina
 # All rights reserved
 # 
 # Redistribution and use in source and binary forms, with or without
@@ -28,35 +28,35 @@
 # THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
 
-CC=		@CC@
-CFLAGS=		@CFLAGS@
-CPPFLAGS=	-I.. @CPPFLAGS@
+SUBDIRS=		OpenBSD OpenBSD-devel
+MSYSLOG_VERSION=	@MSYSLOG_VERSION@
+PORT_PREFIX=		msyslog_port
 
-INSTALL=	@INSTALL@
-INSTALL_DIR=	@prefix@/sbin
+all: ports
 
-PROG=		peochk
-SRCS=		peochk.c ../options.c @HASH_SRCS@
-OBJS=		$(SRCS:.c=.o)
+port ports: checkports
+.for i in ${SUBDIRS}
+	@cd ${i} && make clean && ${MAKE} DISTDIR=../.. makesum && \
+		cd - && tar -z -c -s \
+		'/${i}/${PORT_PREFIX}${i:S/OpenBSD//}-${MSYSLOG_VERSION}/' \
+		-f ../${PORT_PREFIX}${i:S/OpenBSD//}-${MSYSLOG_VERSION}.tgz \
+		`find ${i}/ -type f | egrep -v "Makefile.in|CVS|PLIST.in"` && \
+		echo ${i} port tarball created at ${PORT_PREFIX}${i:S/OpenBSD//}-${MSYSLOG_VERSION}.tgz
+.endfor
 
-all: $(PROG) $(OBJS)
+checkports:
+	@if ! test -e /usr/ports/infrastructure/mk/bsd.port.mk; \
+		then echo "Missing OpenBSD ports tree."; exit 1; fi
 
-$(OBJS): $(SRCS)
-	$(CC) $(CFLAGS) $(CPPFLAGS) -c $(@:.o=.c) -o $@
+port-clean clean:
+.for i in ${SUBDIRS}
+	@-cd ${i} && make clean
+	-rm -rf ../${PORT_PREFIX}${i:S/OpenBSD//}-${MSYSLOG_VERSION}.tgz
+.endfor
 
-$(PROG): $(OBJS)
-	$(CC) $(CFLAGS) $(OBJS) -o $@
-
-.PHONY: clean distclean
-clean:
-	-rm -f $(OBJS) core *.core $(PROG)
-
-distclean: clean
-	-rm -f Makefile
-
-install:
-	@if [ ! -d $(INSTALL_DIR) ]; then \
-		mkdir -p $(INSTALL_DIR); \
-	fi
-	-$(INSTALL) ${PROG} $(INSTALL_DIR)
+port-distclean distclean: clean
+	-rm -rf Makefile OpenBSD/pkg/PLIST
+.for i in ${SUBDIRS}
+	-rm -rf ${i}/Makefile ${i}/files
+.endfor
 
